### ISSUE TITLE
Entities in HA

### ISSUE THREAD

**Issue by ralle6677** [dfigus/addon-solarflow-control#44]
Hello, thank you very much for the implementation directly in HA.I installed the addon and according to log Solarflow-Control works correctly. 

Now maybe a stupid question. The entities also seem to be created in HA. However, no current values arrive. According to MQTT Explorer, however, these are sent. Do I still have to do something so that I also have the values in HA and thus can control the whole thing?

Thank you!!
VG!
Ralf

**Comment by dfigus** [comment]
Did you enable the MQTT integration in HA? The values are pushed to your MQTT broker and HA needs to pick it up from there.

**Comment by ralle6677** [comment]
Das ist möglicherweise der Punkt. Da ich meinen Mosquitto Addon in HA nicht ohne Authentifizierung laufen lassen möchte, hab ich unter Docker noch einen zweiten Installiert.
